name: Assign Reviewer to PR

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          reviewers: 'e5l'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
